--- @type Menu
--- Feel free to change all Coming Soon
--- or contact me on Instagram @yxukia for help

local menu = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0, 'size-125', 'pdrp', 'menuv', 'example_namespace')
local menu2 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu3 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu4 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu5 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu6 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu7 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu8 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu9 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu10 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu11 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu12 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu13 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu14 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu15 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu16 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu17 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu18 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu19 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu20 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu21 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu22 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu23 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu24 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu25 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu26 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu27 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu28 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu29 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu30 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)
local menu31 = MenuV:CreateMenu(' ', 'Vehicle Spawn Menu', 'topright', 255, 0, 0)



--- Events

menu:On('open', function()
    menu:ClearItems()
    menu:AddButton({ icon = '👑', label = 'Coming Soon', value = menu13, description = 'Coming Soon' })
    local menu_button = menu:AddButton({ icon = '💰', label = 'Coming Soon', value = menu2, description = 'Coming Soon' })
    local menu_button = menu:AddButton({ icon = '🔑', label = 'Coming Soon', value = menu3, description = 'Coming Soon' })
    menu:AddButton({ icon = '🚓', label = 'Coming Soon', value = menu14, description = 'Coming Soon' })
    end)

menu2:On('open', function() --packs
    menu2:ClearItems()
    local menu2 = menu2:AddButton({ icon = '💎', label = 'Coming Soon', value = menu4, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '💰', label = 'Coming Soon', value = menu5, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '💸', label = 'Coming Soon', value = menu6, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '💵', label = 'Coming Soon', value = menu7, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '🚓', label = 'Coming Soon', value = menu8, description = 'Coming Soon' })
    local menu2  = menu2:AddButton({ icon = '🏎️', label = 'Coming Soon', value = menu9, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '🚘', label = 'Coming Soon', value = menu10, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '🛻', label = 'Coming Soon', value = menu11, description = 'Coming Soon' })
    local menu2 = menu2:AddButton({ icon = '🛵', label = 'Coming Soon', value = menu12, description = 'Coming Soon' })
    end)

menu3:On('open', function() -- Menu 5
    menu3:ClearItems()
    local menu3 = menu3:AddButton({ icon = '🏴', label = 'Coming Soon', value = menu24, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🎅🏻', label = 'Coming Soon', value = menu25, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🚀', label = 'Coming Soon', value = menu26, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🦇 ', label = 'Coming Soon', value = menu27, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🚛', label = 'Coming Soon', value = menu28, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🐠', label = 'Coming Soon', value = menu29, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🍪', label = 'Coming Soon', value = menu30, description = 'Coming Soon' })
    local menu3 = menu3:AddButton({ icon = '🍻', label = 'Coming Soon', value = menu31, description = 'Coming Soon' })
    end)

menu4:On('open', function() -- Menu 4
    menu4:ClearItems()
    local dsamwidec8 = menu4:AddButton({ label = 'Chevy Corvette', description = 'Widebody C8 Chevy Corvette' })
    dsamwidec8:On('select', function() deleteVeh() end)
    dsamwidec8:On('select', function() spawnCar("amwidec8") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu4:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu5:On('open', function() -- Menu 5
    menu5:ClearItems()
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu5:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu6:On('open', function() -- Menu 6
    menu6:ClearItems()
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu6:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu7:On('open', function() -- Menu 7
    menu7:ClearItems()
    local Comingsoon = menu7:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon ") end)
    local Comingsoon = menu7:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon ") end)
    local Comingsoon = menu7:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon ") end)
    local Comingsoon = menu7:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon ") end)
    end)

menu8:On('open', function() -- menu 8
    menu8:ClearItems()
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu8:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu9:On('open', function() -- Menu 9
    menu9:ClearItems()
    local Comingsoon = menu9:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("f48Comingsoon8pista") end)
    local Comingsoon = menu9:AddButton({ label = 'Comingsoon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Comingsoon ', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Comingsoon', description = '2024 Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu9:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu10:On('open', function() -- menu 10
    menu10:ClearItems()
    local Comingsoon = menu10:AddButton({ label = 'Comingsoon', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Comingsoon', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Comingsoon', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Comingsoon', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Comingsoon', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Comingsoon', description = 'Comingsoon ' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu10:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu11:On('open', function() -- Menu 11
    menu11:ClearItems()
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu11:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu12:On('open', function() -- menu 12
    menu12:ClearItems()
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu12:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu13:On('open', function() -- Menu 13
    menu13:ClearItems()
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu13:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)



menu14:On('open', function() -- Menu 14
    menu14:ClearItems()
    menu14:AddButton({ icon = '👮🏻', label = 'Coming Soon', value = menu15, description = 'Coming Soon' })
    menu14:AddButton({ icon = '👮🏻', label = 'Coming Soon', value = menu16, description = 'Coming Soon' })
    menu14:AddButton({ icon = '👮🏻', label = 'Coming Soon', value = menu17, description = 'Coming Soon' })
    menu14:AddButton({ icon = '👮🏻', label = 'Coming Soon', value = menu19, description = 'Coming Soon' })
    menu14:AddButton({ icon = '🚨', label = 'Coming Soon', value = menu20, description = 'Coming Soon' })
    menu14:AddButton({ icon = '🪖', label = 'Coming Soon', value = menu21, description = 'Coming Soon' })
    menu14:AddButton({ icon = '🚨', label = 'Coming Soon', value = menu22, description = 'Coming Soon' })
    menu14:AddButton({ icon = '🚨', label = 'Coming Soon', value = menu23, description = 'Coming Soon' })
    end)

menu15:On('open', function() -- Menu 15
    menu15:ClearItems()
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu15:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu16:On('open', function() -- Menu 16
    menu16:ClearItems()
    local Comingsoon = menu16:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu16:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu16:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu16:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu16:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu17:On('open', function() -- Menu 17
    menu17:ClearItems()
    local Comingsoon = menu17:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu17:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu17:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu17:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu17:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu17:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu19:On('open', function() -- Menu 19
    menu19:ClearItems()
    local Comingsoon = menu19:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu19:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu19:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu19:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu19:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu20:On('open', function() -- Menu 20
    menu20:ClearItems()
    local Comingsoon = menu20:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu20:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu20:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu20:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu20:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu20:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu21:On('open', function() -- menu 21
    menu21:ClearItems()
    local Comingsoon = menu21:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu21:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu21:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu21:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu22:On('open', function() -- Menu 22
    menu22:ClearItems()
    local Comingsoon = menu22:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu22:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu22:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu22:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu22:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu22:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu23:On('open', function() -- Menu 23
    menu23:ClearItems()
    local Comingsoon = menu23:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu23:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu23:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu23:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu24:On('open', function() -- Menu 24
    menu24:ClearItems()
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu24:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)
    
menu25:On('open', function() -- Menu 25
    menu25:ClearItems()
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu25:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)
    
menu26:On('open', function() -- Menu 26
    menu26:ClearItems()
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu26:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu27:On('open', function() -- Menu 27
    menu27:ClearItems()
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu27:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)
 
menu28:On('open', function() -- Menu 28
    menu28:ClearItems()
    local Comingsoon = menu28:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu28:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu28:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu28:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu28:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu28:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)   

menu29:On('open', function() -- Menu 29
    menu29:ClearItems()
    local Comingsoon = menu29:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu29:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu29:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu29:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu29:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu29:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end) 

menu30:On('open', function() -- Menu 30
    menu30:ClearItems()
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu30:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end)

menu31:On('open', function() -- Menu 31
    menu31:ClearItems()
    local pkgt86 = menu31:AddButton({ label = 'GT86', description = 'GT86' })
    pkgt86:On('select', function() deleteVeh() end)
    pkgt86:On('select', function() spawnCar("gt86") end)
    local Comingsoon = menu31:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu31:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu31:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu31:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    local Comingsoon = menu31:AddButton({ label = 'Coming Soon', description = 'Comingsoon' })
    Comingsoon:On('select', function() deleteVeh() end)
    Comingsoon:On('select', function() spawnCar("Comingsoon") end)
    end) 

menu:OpenWith('KEYBOARD', 'F9')

function deleteVeh()
    local ped = GetPlayerPed(-1)
    if (DoesEntityExist(ped) and not IsEntityDead(ped)) then 
        local pos = GetEntityCoords(ped)
  
    if (IsPedSittingInAnyVehicle(ped)) then 
      local handle = GetVehiclePedIsIn(ped, false)
      NetworkRequestControlOfEntity(handle)
      SetEntityHealth(handle, 100)
      SetEntityAsMissionEntity(handle, true, true)
      SetEntityAsNoLongerNeeded(handle)
      DeleteEntity(handle)
        end
    end
  end
  
  
  function spawnCar(car)
      local car = GetHashKey(car)
  
      RequestModel(car)
      while not HasModelLoaded(car) do
          RequestModel(car)
          Citizen.Wait(50)
      end
  
      local x, y, z = table.unpack(GetEntityCoords(PlayerPedId(), false))
      local vehicle = CreateVehicle(car, x + 2, y + 2, z + 1, GetEntityHeading(PlayerPedId()), true, false)
      SetPedIntoVehicle(PlayerPedId(), vehicle, -1)
      
      SetEntityAsNoLongerNeeded(vehicle)
      SetModelAsNoLongerNeeded(vehicleName)
      
  end
